### PR TITLE
Handled transfer of media and other JSON stored property values on the settings section of block list editors.

### PR DESCRIPTION
**Pull request by AndyButland**
This problem is raised in [issue #86](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/86) is the images used on the "Settings" tab of block list editor items are not getting transferred.

It seems the cause of this is that there's a difference in how the CMS serializes the property editor values for block list items between the "content" and the "settings" tabs.

For example, this is how the value serialized to the database looks when we have an image on "content" and "settings":

```
{
   "layout":{
      "Umbraco.BlockList":[
         {
            "contentUdi":"umb://element/b99d450dd3754405be46fbc72155c17c",
            "settingsUdi":"umb://element/3c7c779e77c34c39bc3355e996f10940"
         }
      ]
   },
   "contentData":[
      {
         "contentTypeKey":"9dee4fc1-347f-42b2-ba5b-784b09cd959a",
         "udi":"umb://element/b99d450dd3754405be46fbc72155c17c",
         "title":"Item A",
         "image":"[\r\n  {\r\n    \"key\": \"98ef58be-8dab-4e3a-ac98-4221eba36c3c\",\r\n    \"mediaKey\": \"fa763e0d-0ceb-408c-8720-365d57e06e32\",\r\n    \"crops\": [],\r\n    \"focalPoint\": {\r\n      \"left\": 0.5,\r\n      \"top\": 0.5\r\n    }\r\n  }\r\n]"
      }
   ],
   "settingsData":[
      {
         "contentTypeKey":"a055817c-6ace-43cb-abab-e810ca8aec82",
         "udi":"umb://element/3c7c779e77c34c39bc3355e996f10940",
         "title":"Setting A",
         "image":[
            {
               "key":"b1f9b417-170a-4c4a-891d-24deda76ac2b",
               "mediaKey":"eee91c05-b2e8-4031-a056-dcd7f28eff89",
               "crops":[                  
               ],
               "focalPoint":{
                  "left":0.5,
                  "top":0.5
               }
            }
         ]
      }
   ]
}
```

I.e for "content" we have the JSON value serialized as a string, but for "settings" it's stored as a JSON structure (a JToken).

I'm not really sure why this is, but given this is how the data is currently stored we can't really fix this in the CMS due to all the data already stored in people's Umbraco installations, even if ideally they would be aligned.

So this PR adds a couple of checks for when we are working with JSON data under "settings" and amends the conversion to and from the artifact as appropriate.

To Test:

- Create two element types, each with a media picker on it.
- Configure a block list data type that uses the two elements types as the "content" and "settings" model
- Use this data type on a document type.
- Deploy schema to the destination environment and trigger an extraction
- Create a content item based on the document type and populate the media picker on both "content" and "settings"
- Confirm that the media is transferred and populated in the destination environment.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
We should ensure this Block List value connector supports both the current JSON structure for the settings data, but also the serialized string value. That would ensure it still works when the actual bug in the CMS is fixed (I've already started on a fix while debugging the issue, see: https://github.com/umbraco/Umbraco-CMS/commit/d8f4798baef01f41e6b601479f6baa58a66f4281).

As mentioned in https://github.com/umbraco/Umbraco.Deploy.Issues/issues/86#issuecomment-968902570, the way we currently store `contentData` isn't correct either, as it now contains a serialized string representation (that requires escaping and for some editors also includes whitespace).

Another thing to consider: the settings data that's currently stored is what the backoffice editor expects, not what should actually be stored in the database. This can result in value connectors receiving incompatible data and throwing exceptions while trying to convert it to a deployable artifact.

**Review by ronaldbarendse — CHANGES_REQUESTED** [review]
Lets first fix the CMS issue and then ensure Deploy correctly supports transferring the old and new content/settings data format.

**Comment by AndyButland** [comment]
It looks like this won't be required if [this fix](https://github.com/umbraco/Umbraco-CMS/pull/11722) is applied in the CMS.

**Comment by AndyButland** [comment]
I've retested this with the CMS fix applied and see that the media picker details are transferred for block list items now whether stored under "Content" or "Settings.  So we don't need this PR.

**Pull request closed without merging**
