### PR TITLE
feat: Added in codes for the DTGE cell value connector

### PR DESCRIPTION
**Pull request by jericyuen**
Ported DTGE cell value connector from V7, amended the code

### CODE REVIEW

**Comment by Jeavon** [comment]
@clausjensen Jeric has also added some fixes to the NestedContent connector in this PR one of our clients experienced when transferring content between environments...

**Comment by Jacob87** [comment]
I am very interested in this value connector. Do you think it could be merged soon-ish? And which version could it then end up in?

**Comment by Jeavon** [comment]
@AndyButland any chance you might pick this one up otherwise I think perhaps we should package it separately...

**Comment by AndyButland** [comment]
Hi - yes, I think we can and should include this.  Sorry - it's just not come up on my radar yet so thanks for flagging.

**Comment by AndyButland** [comment]
Thanks very much for this.  Have merged in - will do some testing, then make available in a release.  I'll update again here once it's out.

**Comment by AndyButland** [comment]
This is out now in 4.1.0 available [here](https://www.nuget.org/packages/UmbracoDeploy.Contrib/).

**Comment by AndyButland** [comment]
PR that hopefully fixes these issues is [here](https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/49).

**Pull request merged**
