### PR TITLE
Cogworks.Meganav connector

### PR DESCRIPTION
**Pull request by ronaldbarendse**
Although Cogworks has 'Umbraco Cloud / Courier' support listed as coming soon, I'm using this great property editor _right now_ on websites running on UC: https://github.com/thecogworks/meganav.  So I decided to write the connector myself and add it to this project (to keep additional assemblies to a minimum)... The connector itself is simple: replace id's with UDIs (and reverse on deploy) and track the dependencies.

I also ignored the Umbraco Deploy content files that are restored from NuGet and fixed 3 warnings (unused `ex` variable and 2 fields that should be properties).

### CODE REVIEW

**Comment by clausjensen** [comment]
Thanks for the PR @ronaldbarendse 
I'll get this reviewed as soon as possible and have it merged in 😃

Not sure what the status is on Cogworks doing any work for this - so I'd say this is a good base for them if they want to contribute later on.

**Comment by ronaldbarendse** [comment]
Great! I've used/tested this on multiple client sites and all Meganav links are correctly restored (e.g. with environment specific IDs to the same pages/UDIs).

I've not had any contact with the developers from Cogworks, but AFAIK the data model hasn't changed, so it should work on all versions. And having the connector here seems like the best place, but I'll raise an issue just to check that with them! 😄

**Comment by clausjensen** [comment]
Cool!
It _is_ a pretty awesome package .. they only thing actually holding me off from using it more was the missing connector that I never really got around to creating. Thanks for getting the ball rolling on this 😄

**Comment by ronaldbarendse** [comment]
Any progress on getting this merged in and creating a new release?

**Comment by clausjensen** [comment]
Hi @ronaldbarendse 
The Cloud team will be picking up this task for review - I think @KennethJakobsen is on it.
Hopefully it will not take too long before this can be tested and merged in.

**Comment by kows** [comment]
Any ETA on this?

**Comment by clausjensen** [comment]
@ronaldbarendse Thanks a lot again for the PR - I've merged it in with some minor updates 😃
Sorry for the delay on getting it reviewed and merged!

**Comment by ronaldbarendse** [comment]
@clausjensen Thanks! I didn't know about the `Direction` enum, makes total sense to move the parsing to a single function when using that 👍

**Comment by clausjensen** [comment]
@ronaldbarendse Yep not all the connectors use it - it's mostly used in the macro parser stuff where the logic is a bit more complex, to avoid having to update the logic in two places when the difference between two methods is really small 😃

**Pull request merged**
