### PR TITLE
Handling Nested Content property inside Leblend Grid Element

### PR DESCRIPTION
**Pull request by elglogins**
If Leblender grid element contains property of Nested Object type. For some reason it is not array of NestedContentValue, but a single object.

`Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Umbraco.Deploy.Contrib.Connectors.ValueConnectors.NestedContentValueConnector+NestedContentValue[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'name', line 2, position 9.`

### CODE REVIEW

**Comment by bjarnef** [comment]
I just had the same issue as you @elglogins 😁 

I have no issues rendering the content from Nested Content inside LeBlender, but it fails when deploying (maybe also when restoring).

image

image

**Comment by bjarnef** [comment]
This issue also prevent to deploy children of this node, e.g. if this LeBlender grid editor with Nested Content is placed on Frontpage, then deploy of any child node fails.

If I then remove this grid editor from Frontpage, I can deploy child nodes successfully.

**Comment by warrenbuckley** [comment]
Thanks for the PR @elglogins & your notes @bjarnef on this issue.
I am not so familiar with LeBlender, are you able to provide some steps in order to reproduce this error so I have the same configuration & setup for me to test, confirm & verify the fix works as intended please :)

**Comment by clausjensen** [comment]
Thanks for the PR @elglogins :)

**Pull request merged**
